# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        build:
            context: './vendor/laravel/sail/runtimes/${PHP_VERSION:-8.1}'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-${PHP_VERSION:-8.1}/app'
        container_name: "${APP_URL:-javan-assessment-1-app}"
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${FORWARD_APP_PORT:-80}:${APP_PORT:-80}'
            - '${FORWARD_VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - app
        depends_on:
            - mariadb
    mariadb:
        image: "mariadb:${MARIADB_VERSION:-10}"
        container_name: "${DB_HOST:-javan-assessment-1-mariadb}"
        ports:
            - '${FORWARD_DB_PORT:-3306}:${DB_PORT:-3306}'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE:-javan_assessment_1}'
            MYSQL_USER: '${DB_USERNAME:-root}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'app-mariadb:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - app
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
networks:
    app:
        driver: bridge
volumes:
    app-mariadb:
        driver: local
